feat: neue Spezialkarten 7.5 und 9.75 ohne Sonderaktion
TecToast/games pull request #2
Opened 2024-10-07 12:58 UTC by GunnarHerbert

Achtung: noch nicht ausreichend getestet

2024-10-07 13:13 UTC, TecToast requested changes

2024-10-07 13:13 UTC, TecToast commented on utils/wizard/types.ts
> +  for (let i = 1; i <= 3; i++) {
7 1/2 und 9 3/4 haben ihre eigenen Values, nicht 2 und 3

2024-10-07 13:13 UTC, TecToast commented on composables/wizard/firstcard.ts
> +          isCard(c.card, "Nichts", 2) ||
welche Karte ist "Nichts 2"

2024-10-07 13:13 UTC, TecToast commented on composables/wizard/firstcard.ts
> +          isCard(c.card, "Spezial", 3),
Warum? Mal abgesehen davon, dass Spezial 3 sowieso nicht existiert, aber diese Karten sollen ja die First Card setzen wenn sie zuerst liegen, im Gegensatz zum Narr

2024-10-07 13:13 UTC, TecToast commented on composables/wizard/firstcard.ts
>      }
Technically auch falsch, aber den bombFirst Check habe ich bei mir überarbeitet, werde ich dann einfach nach dem Merge patchen

2024-10-07 13:57 UTC, GunnarHerbert commented on utils/wizard/types.ts
> +  for (let i = 1; i <= 3; i++) {
Danke, habs gerade korrigiert

2024-10-07 14:00 UTC, GunnarHerbert commented on composables/wizard/firstcard.ts
> +          isCard(c.card, "Nichts", 2) ||
Sollte eigtl. '(c.card, "Spezial", 2)' heißen, aber das ist ohnehin überfällig. Habe die Abfragen gelöscht, sodass nur noch nach Nichts, Narr und Bomb geschaut wird

2024-10-07 14:01 UTC, GunnarHerbert commented on composables/wizard/firstcard.ts
> +          isCard(c.card, "Spezial", 3),
Jap,  das hatte ich gemacht bevor ich die genauen Regeln kannte 😅. Wurde aber jetzt überarbeitet

2024-10-07 14:01 UTC, GunnarHerbert commented on composables/wizard/firstcard.ts
>      }
👍

2024-10-07 14:09 UTC, TecToast approved these changes
Damit sehen die bisherigen Changes gut aus :)

2024-10-19 21:16 UTC, TecToast requested changes

2024-10-19 21:16 UTC, TecToast commented on components/wizard/Card.vue
> +    props.firstCard == NOTHINGCARD ||
Warum genau hast du den First Card Zauberer Check rausgenommen und dafür nen nicht benötigten Nothing Card Check eingebaut?
(Wenn die First Card die Nothing Card ist wird die playerCards.every Condition wahr weil jede Kartenfarbe von dir != Nichts ist)

2024-10-19 21:37 UTC, TecToast approved these changes

2024-10-19 21:40 UTC, merged